name: Docker Image CI

on:
  push:
    branches: 
      - $default-branch
      - development
      - master
  # Run tests for any PRs
  pull_request:

env:
  IMAGE_NAME: httpdiff

jobs:
  lint-docker-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: lint zammad dockerfile
      uses: brpaz/hadolint-action@master
      with:
        dockerfile: Dockerfile
  build:
    needs:
      - lint-docker-file
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run:  docker build . --file Dockerfile --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" --tag ${IMAGE_NAME}
    - name: Test the Docker image
      run: |
        CONTAINER_OUTPUT="$(docker run --rm -t ${IMAGE_NAME} -help)"
        echo "${CONTAINER_OUTPUT}"
        TEST_STRING="$(echo ${CONTAINER_OUTPUT} | head -1 | cut -d' ' -f1)"
        echo "${TEST_STRING}"
        if ! [ "${TEST_STRING}" = "httpdiff" ]; then exit 1; fi
